import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';

export const Verify = () => {
  const [fingerprint, setFingerprint] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);
  const [verificationResult, setVerificationResult] = useState<{
    found: boolean;
    voteData?: {
      timestamp: string;
      blockHash: string;
      transactionHash: string;
      ipfsHash: string;
      encrypted: boolean;
    };
  } | null>(null);

  const downloadProof = () => {
    if (!verificationResult?.found || !verificationResult.voteData) {
      toast.error('No verified vote data to download');
      return;
    }

    const pdfContent = `
e-VS VOTE VERIFICATION PROOF
=============================

Generated: ${new Date().toLocaleString()}
Digital Fingerprint: ${fingerprint}

VOTE DETAILS:
- Timestamp: ${new Date(verificationResult.voteData.timestamp).toLocaleString()}
- Status: ✓ Recorded and encrypted
- Verification: ✓ Confirmed on blockchain

BLOCKCHAIN DATA:
- Block Hash: ${verificationResult.voteData.blockHash}
- Transaction Hash: ${verificationResult.voteData.transactionHash}  
- IPFS Hash: ${verificationResult.voteData.ipfsHash}

SECURITY STATUS:
✓ Vote encrypted with AES-256-GCM
✓ Stored on decentralized IPFS
✓ Blockchain immutability guaranteed
✓ Zero-knowledge proof verified

This document serves as proof that your vote was successfully recorded and verified on the blockchain.

Generated by e-VS (e Voting System)
    `;

    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `eVS-Vote-Proof-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);

    toast.success('Vote proof downloaded successfully!');
  };

  const verifyVote = async () => {
    if (!fingerprint.trim()) {
      toast.error('Please enter your digital fingerprint');
      return;
    }

    setIsVerifying(true);
    setVerificationResult(null);

    try {
      // Simulate blockchain verification
      await new Promise(resolve => setTimeout(resolve, 2500));

      // Mock successful verification
      const mockResult = {
        found: true,
        voteData: {
          timestamp: new Date().toISOString(),
          blockHash: '0x7a8f9b2c4d1e6f3a8b5c9d2e7f4a1b6c3d8e5f2a9b4c7d0e3f6a8b1c4d7e0f3a6b9c',
          transactionHash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d',
          ipfsHash: 'QmT4AjRiS2pXwG9sDhZ8cE1VuM7BkLq3NrF5HxJ6KpO8sT9Y',
          encrypted: true
        }
      };

      setVerificationResult(mockResult);
      
      toast.success('Vote verification completed!', {
        description: 'Your vote was found on the blockchain.'
      });
    } catch (error) {
      toast.error('Verification failed. Please check your fingerprint.');
      setVerificationResult({ found: false });
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <div className="min-h-screen p-6">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold matrix-text mb-4">
            <span className="animate-digital-form">VOTE VERIFICATION</span>
          </h1>
          <p className="text-matrix-glow text-lg">
            Verify that your vote was recorded on the blockchain
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Verification Input */}
          <Card className="matrix-terminal">
            <CardHeader>
              <CardTitle className="matrix-text">
                <span className="text-matrix-bright mr-2">&gt;</span>
                Enter Digital Fingerprint
              </CardTitle>
              <CardDescription className="text-matrix-glow">
                Use the fingerprint generated during registration to verify your vote
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="fingerprint" className="matrix-text">
                  Digital Fingerprint (SHA-256 Hash)
                </Label>
                <Input
                  id="fingerprint"
                  type="text"
                  placeholder="Enter your 64-character hash..."
                  value={fingerprint}
                  onChange={(e) => setFingerprint(e.target.value)}
                  className="matrix-input font-mono text-sm"
                  maxLength={64}
                />
                <p className="text-xs text-matrix-glow">
                  This is the SHA-256 hash of your ID document generated during registration
                </p>
              </div>

              {isVerifying ? (
                <div className="text-center py-8">
                  <div className="animate-glitch text-2xl matrix-text mb-4">
                    VERIFYING...
                  </div>
                  <div className="space-y-2 font-mono text-sm text-matrix-glow">
                    <div className="animate-pulse">&gt; Searching blockchain...</div>
                    <div className="animate-pulse">&gt; Checking vote records...</div>
                    <div className="animate-pulse">&gt; Validating cryptographic proof...</div>
                  </div>
                </div>
              ) : (
                <Button 
                  onClick={verifyVote}
                  className="matrix-button w-full"
                  disabled={fingerprint.length !== 64}
                >
                  &gt; VERIFY VOTE ON BLOCKCHAIN
                </Button>
              )}
            </CardContent>
          </Card>

          {/* Verification Result */}
          <Card className="matrix-terminal">
            <CardHeader>
              <CardTitle className="matrix-text">
                <span className="text-matrix-bright mr-2">&gt;</span>
                Verification Result
              </CardTitle>
              <CardDescription className="text-matrix-glow">
                Blockchain verification status and vote details
              </CardDescription>
            </CardHeader>
            <CardContent>
              {!verificationResult ? (
                <div className="text-center py-12 text-matrix-glow">
                  <div className="text-4xl mb-4">🔍</div>
                  <p>Enter your digital fingerprint above to verify your vote</p>
                </div>
              ) : verificationResult.found && verificationResult.voteData ? (
                <div className="space-y-6">
                  <div className="text-center">
                    <div className="text-4xl mb-4 animate-matrix-glow">✓</div>
                    <div className="text-2xl matrix-text text-matrix-bright mb-2">
                      VOTE VERIFIED
                    </div>
                    <p className="text-matrix-glow">
                      Your vote was successfully found on the blockchain
                    </p>
                  </div>

                  <div className="space-y-4 text-sm">
                    <div className="p-4 bg-primary/10 rounded border border-primary/30">
                      <div className="font-semibold text-matrix-bright mb-2">Vote Details</div>
                      <div className="space-y-2 font-mono text-xs text-matrix-glow">
                        <div>
                          <span className="text-matrix-bright">Timestamp:</span><br/>
                          {new Date(verificationResult.voteData.timestamp).toLocaleString()}
                        </div>
                        <div>
                          <span className="text-matrix-bright">Status:</span><br/>
                          ✓ Recorded and encrypted
                        </div>
                      </div>
                    </div>

                    <div className="p-4 bg-primary/10 rounded border border-primary/30">
                      <div className="font-semibold text-matrix-bright mb-2">Blockchain Data</div>
                      <div className="space-y-2 font-mono text-xs text-matrix-glow break-all">
                        <div>
                          <span className="text-matrix-bright">Block Hash:</span><br/>
                          {verificationResult.voteData.blockHash.slice(0, 20)}...
                        </div>
                        <div>
                          <span className="text-matrix-bright">Transaction:</span><br/>
                          {verificationResult.voteData.transactionHash.slice(0, 20)}...
                        </div>
                        <div>
                          <span className="text-matrix-bright">IPFS Hash:</span><br/>
                          {verificationResult.voteData.ipfsHash}
                        </div>
                      </div>
                    </div>

                    <div className="p-4 bg-primary/10 rounded border border-primary/30">
                      <div className="font-semibold text-matrix-bright mb-2">Security Status</div>
                      <div className="space-y-1 font-mono text-xs text-matrix-glow">
                        <div>✓ Vote encrypted with AES-256-GCM</div>
                        <div>✓ Stored on decentralized IPFS</div>
                        <div>✓ Blockchain immutability guaranteed</div>
                        <div>✓ Zero-knowledge proof verified</div>
                      </div>
                    </div>
                  </div>

                  <div className="flex justify-center">
                    <Button 
                      className="matrix-button flex-1"
                      onClick={downloadProof}
                    >
                      &gt; Download Proof
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="text-center py-12">
                  <div className="text-4xl mb-4 text-red-500">✗</div>
                  <div className="text-xl matrix-text text-red-400 mb-2">
                    VOTE NOT FOUND
                  </div>
                  <p className="text-matrix-glow text-sm">
                    No vote record found for this fingerprint.<br/>
                    Please check your digital fingerprint and try again.
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* How Verification Works */}
        <Card className="matrix-terminal mt-8">
          <CardHeader>
            <CardTitle className="matrix-text">
              <span className="text-matrix-bright mr-2">&gt;</span>
              How Vote Verification Works
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-8 text-sm">
              <div className="space-y-4 text-matrix-glow">
                <div>
                  <div className="font-semibold text-matrix-bright mb-2">🔍 Lookup Process</div>
                  <div className="space-y-1 font-mono text-xs">
                    <div>&gt; Your fingerprint is used as a lookup key</div>
                    <div>&gt; Blockchain searched for matching vote record</div>
                    <div>&gt; Cryptographic proof verified</div>
                    <div>&gt; Vote integrity confirmed</div>
                  </div>
                </div>

                <div>
                  <div className="font-semibold text-matrix-bright mb-2">🔒 Privacy Protection</div>
                  <div className="space-y-1 font-mono text-xs">
                    <div>&gt; Vote content remains encrypted</div>
                    <div>&gt; Only existence is verified</div>
                    <div>&gt; No voting choice revealed</div>
                    <div>&gt; Anonymous verification guaranteed</div>
                  </div>
                </div>
              </div>

              <div className="space-y-4 text-matrix-glow">
                <div>
                  <div className="font-semibold text-matrix-bright mb-2">⛓️ Blockchain Verification</div>
                  <div className="space-y-1 font-mono text-xs">
                    <div>&gt; Immutable record on distributed ledger</div>
                    <div>&gt; Multiple node confirmation</div>
                    <div>&gt; Timestamp verification</div>
                    <div>&gt; Hash integrity checking</div>
                  </div>
                </div>

                <div>
                  <div className="font-semibold text-matrix-bright mb-2">🌐 IPFS Verification</div>
                  <div className="space-y-1 font-mono text-xs">
                    <div>&gt; Decentralized storage confirmation</div>
                    <div>&gt; Content addressing verified</div>
                    <div>&gt; Distributed availability checked</div>
                    <div>&gt; Encrypted payload validated</div>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};